#!/bin/bash

echo "🎨 Testing Complete Modern Download System Across All Screens"
echo "============================================================="

# Clear all caches
echo "1. 🧹 Clearing all caches..."
pkill -f "metro" || true
rm -rf /tmp/metro-* /tmp/react-native-* /tmp/haste-map-* ~/.metro || true
rm -rf node_modules/.cache || true

# Start Metro with reset cache
echo "2. 🚀 Starting Metro with reset cache..."
npx react-native start --reset-cache &
METRO_PID=$!

echo "✅ Metro started (PID: $METRO_PID)"
echo ""
echo "🎯 Test All Screens with Modern Download System:"
echo ""
echo "📱 CLIENTS SCREEN:"
echo "   • Navigate to Clients screen"
echo "   • Click green download button"
echo "   • Expect: Modern banking-style success modal"
echo ""
echo "📱 STORES SCREEN:"
echo "   • Navigate to Stores screen"
echo "   • Test export button (green)"
echo "   • Test bulk PPT/PDF downloads"
echo "   • Test individual store downloads"
echo "   • Expect: Same modern UI for all downloads"
echo ""
echo "📱 RECCE SCREEN:"
echo "   • Navigate to Recce screen"
echo "   • Test export and bulk downloads"
echo "   • Expect: Consistent modern UI"
echo ""
echo "📱 INSTALLATION SCREEN:"
echo "   • Navigate to Installation screen"
echo "   • Test export and bulk downloads"
echo "   • Expect: Modern download experience"
echo ""
echo "📱 USERS SCREEN:"
echo "   • Navigate to Users screen"
echo "   • Test export button"
echo "   • Expect: Modern download modal"
echo ""
echo "📱 ROLES SCREEN:"
echo "   • Navigate to Roles screen"
echo "   • Test export button"
echo "   • Expect: Banking-style success modal"
echo ""
echo "📱 RFQ SCREEN:"
echo "   • Navigate to RFQ screen"
echo "   • Select stores and generate RFQ"
echo "   • Expect: Modern download experience"
echo ""
echo "📱 EXPORT SCREEN:"
echo "   • Navigate to Export screen"
echo "   • Test any export option"
echo "   • Expect: Modern download system"
echo ""
echo "🎨 EXPECTED CONSISTENT UI FEATURES:"
echo "   ✓ Toast notifications at top of screen"
echo "   ✓ Button progress indicators (25%, 50%, 75%, 100%)"
echo "   ✓ Banking-style success modal with:"
echo "     - Large gradient success icon (green)"
echo "     - 'Download Complete!' title"
echo "     - File info card with size and location"
echo "     - Blue 'Open File' button (primary action)"
echo "     - 'Share' and 'Folder' buttons (secondary)"
echo "     - Professional typography and spacing"
echo "   ✓ Error modal with retry functionality"
echo "   ✓ Files saved to Downloads folder"
echo "   ✓ Native Android download notifications"
echo ""
echo "🔍 CONSOLE LOGS TO WATCH:"
echo "   - 'SimpleDownloadService: Starting download for filename.xlsx'"
echo "   - Progress updates: 25%, 50%, 75%, 100%"
echo "   - 'SimpleDownloadService: Download complete: /path/to/file'"
echo ""
echo "✅ SUCCESS CRITERIA FOR ALL SCREENS:"
echo "   1. Same beautiful modal appears after download"
echo "   2. File is saved to Downloads folder"
echo "   3. 'Open File' button works"
echo "   4. 'Share' button opens share dialog"
echo "   5. 'Folder' button opens Downloads folder"
echo "   6. Consistent experience across ALL screens"
echo "   7. No old-style Alert dialogs"
echo "   8. No 'can only download http/https' errors"
echo ""
echo "🎉 UPDATED SCREENS:"
echo "   ✅ ClientsScreen - Modern DownloadButton"
echo "   ✅ StoresScreen - Modern export & bulk downloads"
echo "   ✅ RecceScreen - Modern export & bulk downloads"
echo "   ✅ InstallationScreen - Modern export & bulk downloads"
echo "   ✅ UsersScreen - Modern export button"
echo "   ✅ RolesScreen - Modern export button"
echo "   ✅ RFQScreen - Modern RFQ generation"
echo "   ✅ ExportScreen - Modern download system"
echo ""
echo "Press Ctrl+C to stop Metro when done testing"

# Wait for user to stop
wait $METRO_PID