import i18n from '../localization/i18n';

// Content translation mappings for API responses
const contentTranslations: Record<string, string> = {
  // Section titles
  'Geeta Bal Sanskar Offline': 'गीता बाल संस्कार ऑफलाइन',
  'Educational': 'शैक्षिक',
  'Spiritual': 'आध्यात्मिक',
  'Devotional': 'भक्ति',
  'Stories': 'कहानियां',
  'Bhajans': 'भजन',
  'Mantras': 'मंत्र',
  'Prayers': 'प्रार्थनाएं',
  'Meditation': 'ध्यान',
  'Yoga': 'योग',
  'Philosophy': 'दर्शन',
  'Wisdom': 'ज्ञान',
  'Teachings': 'शिक्षाएं',
  'Scriptures': 'शास्त्र',
  'Gita': 'गीता',
  'Geeta': 'गीता',
  'Ramayana': 'रामायण',
  'Mahabharata': 'महाभारत',
  'Puranas': 'पुराण',
  'Upanishads': 'उपनिषद',
  'Vedas': 'वेद',
  'Krishna': 'कृष्ण',
  'Rama': 'राम',
  'Hanuman': 'हनुमान',
  'Shiva': 'शिव',
  'Vishnu': 'विष्णु',
  'Durga': 'दुर्गा',
  'Lakshmi': 'लक्ष्मी',
  'Saraswati': 'सरस्वती',
  'Ganesh': 'गणेश',
  'Bal Sanskar': 'बाल संस्कार',
  'Children': 'बच्चे',
  'Kids': 'बच्चे',
  'Family': 'परिवार',
  'Values': 'मूल्य',
  'Culture': 'संस्कृति',
  'Tradition': 'परंपरा',
  'Heritage': 'विरासत',
  'Festivals': 'त्योहार',
  'Celebrations': 'उत्सव',
  'Rituals': 'अनुष्ठान',
  'Ceremonies': 'समारोह',
  'Worship': 'पूजा',
  'Devotion': 'भक्ति',
  'Faith': 'श्रद्धा',
  'Belief': 'विश्वास',
  'Peace': 'शांति',
  'Love': 'प्रेम',
  'Compassion': 'करुणा',
  'Kindness': 'दया',
  'Truth': 'सत्य',
  'Dharma': 'धर्म',
  'Karma': 'कर्म',
  'Moksha': 'मोक्ष',
  'Salvation': 'मुक्ति',
  'Liberation': 'मुक्ति',
  'Enlightenment': 'ज्ञान',
  'Awakening': 'जागृति',
  'Consciousness': 'चेतना',
  'Soul': 'आत्मा',
  'Spirit': 'आत्मा',
  'Divine': 'दिव्य',
  'Sacred': 'पवित्र',
  'Holy': 'पवित्र',
  'Blessed': 'धन्य',
  'Pure': 'शुद्ध',
  'Eternal': 'शाश्वत',
  'Infinite': 'अनंत',
  'Universal': 'सार्वभौमिक',
  'Cosmic': 'ब्रह्मांडीय',
  'Celestial': 'दिव्य',
  'Heavenly': 'स्वर्गीय',
  'Blissful': 'आनंदमय',
  'Peaceful': 'शांतिपूर्ण',
  'Serene': 'शांत',
  'Tranquil': 'शांत',
  'Calm': 'शांत',
  'Gentle': 'कोमल',
  'Soft': 'मृदु',
  'Sweet': 'मधुर',
  'Beautiful': 'सुंदर',
  'Wonderful': 'अद्भुत',
  'Amazing': 'आश्चर्यजनक',
  'Miraculous': 'चमत्कारी',
  'Magical': 'जादुई',
  'Mystical': 'रहस्यमय',
  'Mysterious': 'रहस्यमय',
  'Ancient': 'प्राचीन',
  'Traditional': 'पारंपरिक',
  'Classical': 'शास्त्रीय',
  'Timeless': 'कालातीत',
  'Everlasting': 'चिरस्थायी',
  'Immortal': 'अमर',
  'Undying': 'अमर',
  'Imperishable': 'अविनाशी',
  'Indestructible': 'अविनाशी',
  
  // Common descriptions
  'Govind Bolo Hari Gopal bolo': 'गोविंद बोलो हरि गोपाल बोलो',
  'Spiritual wisdom and guidance': 'आध्यात्मिक ज्ञान और मार्गदर्शन',
  'Divine teachings': 'दिव्य शिक्षाएं',
  'Sacred knowledge': 'पवित्र ज्ञान',
  'Holy scriptures': 'पवित्र शास्त्र',
  'Devotional songs': 'भक्ति गीत',
  'Spiritual stories': 'आध्यात्मिक कहानियां',
  'Ancient wisdom': 'प्राचीन ज्ञान',
  'Divine blessings': 'दिव्य आशीर्वाद',
  'Sacred mantras': 'पवित्र मंत्र',
  'Meditation practices': 'ध्यान अभ्यास',
  'Yoga teachings': 'योग शिक्षाएं',
  'Spiritual practices': 'आध्यात्मिक अभ्यास',
  'Divine knowledge': 'दिव्य ज्ञान',
  'Sacred texts': 'पवित्र ग्रंथ',
  'Spiritual guidance': 'आध्यात्मिक मार्गदर्शन',
  'Holy teachings': 'पवित्र शिक्षाएं',
  'Divine wisdom': 'दिव्य ज्ञान',
  'Spiritual enlightenment': 'आध्यात्मिक ज्ञान',
  'Sacred learning': 'पवित्र शिक्षा',
  'Children education': 'बच्चों की शिक्षा',
  'Moral values': 'नैतिक मूल्य',
  'Character building': 'चरित्र निर्माण',
  'Personality development': 'व्यक्तित्व विकास',
  'Life lessons': 'जीवन की शिक्षा',
  'Wisdom for life': 'जीवन के लिए ज्ञान',
  'Path to happiness': 'खुशी का रास्ता',
  'Inner peace': 'आंतरिक शांति',
  'Self realization': 'आत्म साक्षात्कार',
  'God realization': 'ईश्वर साक्षात्कार',
  'Divine love': 'दिव्य प्रेम',
  'Unconditional love': 'निःस्वार्थ प्रेम',
  'Pure love': 'शुद्ध प्रेम',
  'Eternal love': 'शाश्वत प्रेम',
  'Universal love': 'सार्वभौमिक प्रेम',
  'Compassionate heart': 'करुणामय हृदय',
  'Kind heart': 'दयालु हृदय',
  'Pure heart': 'शुद्ध हृदय',
  'Noble heart': 'उदार हृदय',
  'Generous heart': 'उदार हृदय',
  
  // Missing translations
  'About Us': 'हमारे बारे में',
  'About': 'हमारे बारे में',
  'Splash Screen': 'स्प्लैश स्क्रीन',
  'Nitya Stuti': 'नित्य स्तुति',
  'Satsang': 'सत्संग',
  'Sandhya': 'संध्या',
  'Skip for now': 'अभी छोड़ें',
  'Skip': 'छोड़ें',
  'Email': 'ईमेल',
  'Login': 'लॉगिन',
  'Sign Up': 'साइन अप',
  'Register': 'पंजीकरण',
  'Daily': 'दैनिक',
  'Evening': 'संध्या',
  'Morning': 'प्रातः',
  'Loading': 'लोड हो रहा है',
  'Version': 'संस्करण',
  'Features': 'विशेषताएं',
  'Mission': 'मिशन',
  'Contact': 'संपर्क',
  'Developer Information': 'डेवलपर जानकारी',
  'About the App': 'ऐप के बारे में',
  'Settings': 'सेटिंग्स',
  'Appearance': 'दिखावट',
  'Language': 'भाषा',
  'Help & Support': 'सहायता और समर्थन',
  'Rate App': 'ऐप को रेट करें',
  'Share App': 'ऐप साझा करें',
  'Rate Now': 'अभी रेट करें',
  'Share': 'साझा करें',
  'Cancel': 'रद्द करें',
  'Would you like to rate our app on the store?': 'क्या आप स्टोर पर हमारे ऐप को रेट करना चाहते हैं?',
  'Share Geeta Bal Sanskaar app with your friends and family!': 'गीता बाल संस्कार ऐप को अपने दोस्तों और परिवार के साथ साझा करें!',
  
  // Help & Support page
  'Contact Us': 'हमसे संपर्क करें',
  'Email Support': 'ईमेल सपोर्ट',
  'Website': 'वेबसाइट',
  'Phone Support': 'फोन सपोर्ट',
  'Visit our official website': 'हमारी आधिकारिक वेबसाइट पर जाएं',
  'Frequently Asked Questions': 'अक्सर पूछे जाने वाले प्रश्न',
  'Quick Actions': 'तुरंत कार्य',
  'Report an Issue': 'समस्या की रिपोर्ट करें',
  'Request Feature': 'नई सुविधा का अनुरोध',
  
  // FAQ Questions and Answers
  'How do I download content for offline viewing?': 'ऑफ़लाइन देखने के लिए कंटेंट कैसे डाउनलोड करूं?',
  'Tap the download icon next to any audio, video, or PDF content. Downloaded content will be available in the Downloads section.': 'किसी भी ऑडियो, वीडियो, या PDF कंटेंट के पास डाउनलोड आइकॉन पर टैप करें। डाउनलोड किया गया कंटेंट डाउनलोड सेक्शन में उपलब्ध होगा।',
  'Can I change the app language?': 'क्या मैं ऐप की भाषा बदल सकता हूँ?',
  'Yes! Go to Settings > Language to select from available languages including Hindi, English, and Sanskrit.': 'हाँ! हिंदी, अंग्रेजी और संस्कृत सहित उपलब्ध भाषाओं में से चुनने के लिए सेटिंग्स > भाषा पर जाएं।',
  'How do I switch between light and dark themes?': 'मैं लाइट और डार्क थीम के बीच कैसे स्विच करूं?',
  'Navigate to Settings > Appearance and choose between Light, Dark, or System theme options.': 'सेटिंग्स > दिखावट पर जाएं और लाइट, डार्क, या सिस्टम थीम विकल्पों में से चुनें।',
  'Is the content free to access?': 'क्या कंटेंट मुफ्त में उपलब्ध है?',
  'Yes, all spiritual content including audio lectures, videos, and books are completely free to access.': 'हाँ, ऑडियो व्याख्यान, वीडियो और पुस्तकों सहित सभी आध्यात्मिक कंटेंट पूरी तरह से मुफ्त है।',
  'How do I report a technical issue?': 'मैं तकनीकी समस्या की रिपोर्ट कैसे करूं?',
  'You can contact our support team using the contact options below or send us an email with details about the issue.': 'आप नीचे दिए गए संपर्क विकल्पों का उपयोग करके हमारी सपोर्ट टीम से संपर्क कर सकते हैं या समस्या के बारे में विवरण के साथ हमें ईमेल भेज सकते हैं।',
  
  // Appearance page
  'Light': 'लाइट',
  'Dark': 'डार्क',
  'System': 'सिस्टम',
  
  // About page content
  'Geeta Bal Sanskar is a comprehensive spiritual learning platform that brings the timeless wisdom of the Bhagavad Gita to modern learners. Our app provides access to audio lectures, video content, and digital books to help you on your spiritual journey.': 'गीता बाल संस्कार एक व्यापक आध्यात्मिक शिक्षा मंच है जो भगवद गीता के कालातीत ज्ञान को आधुनिक शिक्षार्थियों तक पहुंचाता है। हमारा ऐप आपकी आध्यात्मिक यात्रा में मदद करने के लिए ऑडियो व्याख्यान, वीडियो कंटेंट और डिजिटल पुस्तकों तक पहुंच प्रदान करता है।',
  '• Audio lectures and spiritual discourses': '• ऑडियो व्याख्यान और आध्यात्मिक प्रवचन',
  '• Video content and teachings': '• वीडियो कंटेंट और शिक्षाएं',
  '• Digital books and PDFs': '• डिजिटल पुस्तकें और PDF',
  '• Multiple language support': '• कई भाषाओं का समर्थन',
  '• Dark and light theme options': '• डार्क और लाइट थीम विकल्प',
  '• Offline content access': '• ऑफ़लाइन कंटेंट एक्सेस',
  'Our mission is to make spiritual knowledge accessible to everyone, everywhere. We believe that the teachings of the Bhagavad Gita can transform lives and bring peace, wisdom, and happiness to all who seek it.': 'हमारा मिशन आध्यात्मिक ज्ञान को हर जगह, हर किसी के लिए उपलब्ध कराना है। हम मानते हैं कि भगवद गीता की शिक्षाएं जीवन को बदल सकती हैं और उन सभी के लिए शांति, ज्ञान और खुशी ला सकती हैं जो इसे खोजते हैं।',
  'Login Credentials (Demo)': 'लॉगिन क्रेडेंशियल (डेमो)',
  'Email: demo@gbs.org.in': 'ईमेल: demo@gbs.org.in',
  'Password: demo123': 'पासवर्ड: demo123',
  'Email: support@gbs.org.in': 'ईमेल: support@gbs.org.in',
  'Website: gbs.org.in': 'वेबसाइट: gbs.org.in',
  '© 2024 Geeta Bal Sanskar. All rights reserved.': '© 2024 गीता बाल संस्कार। सभी अधिकार सुरक्षित।',
  
  // Common UI elements
  'Home': 'होम',
  'Categories': 'श्रेणियां',
  'Bookmarks': 'बुकमार्क',
  'Downloads': 'डाउनलोड',
  'Search': 'खोजें',
  'Profile': 'प्रोफाइल',
  'Account': 'खाता',
  'Logout': 'लॉगआउट',
  'Back': 'वापस',
  'Next': 'अगला',
  'Previous': 'पिछला',
  'Continue': 'जारी रखें',
  'Save': 'सेव करें',
  'Delete': 'डिलीट करें',
  'Edit': 'संपादित करें',
  'Add': 'जोड़ें',
  'Remove': 'हटाएं',
  'Close': 'बंद करें',
  'Open': 'खोलें',
  'Play': 'चलाएं',
  'Pause': 'रोकें',
  'Stop': 'बंद करें',
  'Replay': 'दोबारा चलाएं',
  'Download': 'डाउनलोड',
  'Upload': 'अपलोड',
  'Refresh': 'रिफ्रेश',
  'Retry': 'पुनः प्रयास',
  'Error': 'त्रुटि',
  'Success': 'सफलता',
  'Warning': 'चेतावनी',
  'Info': 'जानकारी',
  'Yes': 'हाँ',
  'No': 'नहीं',
  'OK': 'ठीक है',
  'Done': 'हो गया',
  'Finish': 'समाप्त',
  'Start': 'शुरू करें',
  'Begin': 'आरंभ करें',
  'End': 'अंत',
  'Complete': 'पूर्ण',
  'Incomplete': 'अधूरा',
  'Available': 'उपलब्ध',
  'Unavailable': 'अनुपलब्ध',
  'Online': 'ऑनलाइन',
  'Offline': 'ऑफलाइन',
  'Connected': 'जुड़ा हुआ',
  'Disconnected': 'डिस्कनेक्ट',
  'Welcome': 'स्वागत',
  'Hello': 'नमस्ते',
  'Goodbye': 'अलविदा',
  'Thank you': 'धन्यवाद',
  'Please': 'कृपया',
  'Sorry': 'क्षमा करें',
  'Excuse me': 'माफ करें',
  
  // Media types
  'Audio': 'ऑडियो',
  'Video': 'वीडियो',
  'Image': 'छवि',
  'Book': 'पुस्तक',
  'PDF': 'पीडीएफ',
  'Music': 'संगीत',
  'Song': 'गाना',
  'Album': 'एल्बम',
  'Artist': 'कलाकार',
  'Author': 'लेखक',
  'Title': 'शीर्षक',
  'Description': 'विवरण',
  'Duration': 'अवधि',
  'Size': 'आकार',
  'Date': 'तारीख',
  'Time': 'समय',
  'Today': 'आज',
  'Yesterday': 'कल',
  'Tomorrow': 'कल',
  'Week': 'सप्ताह',
  'Month': 'महीना',
  'Year': 'वर्ष',
  'Recently Played': 'हाल ही में चलाया गया',
  'Now Playing': 'अभी चल रहा है',
  'Up Next': 'अगला',
  'Playlist': 'प्लेलिस्ट',
  'Queue': 'कतार',
  'Shuffle': 'शफल',
  'Repeat': 'दोहराएं',
  'Volume': 'आवाज़',
  'Mute': 'म्यूट',
  'Unmute': 'अनम्यूट',
  'Full Screen': 'पूरी स्क्रीन',
  'Exit Full Screen': 'पूरी स्क्रीन से बाहर निकलें',
  'Preferences': 'पसंद',
  'Options': 'विकल्प',
  'Menu': 'मेनू',
  'More': 'और',
  'Less': 'कम',
  'Show More': 'और दिखाएं',
  'Show Less': 'कम दिखाएं',
  'See All': 'सभी देखें',
  'View All': 'सभी देखें',
  'Hide': 'छिपाएं',
  'Show': 'दिखाएं',
  'Enable': 'सक्षम करें',
  'Disable': 'अक्षम करें',
  'On': 'चालू',
  'Off': 'बंद',
  'Auto': 'ऑटो',
  'Manual': 'मैनुअल',
  'Default': 'डिफ़ॉल्ट',
  'Custom': 'कस्टम',
  'Reset': 'रीसेट',
  'Clear': 'साफ करें',
  'Empty': 'खाली',
  'Full': 'भरा',
  'New': 'नया',
  'Old': 'पुराना',
  'Recent': 'हालिया',
  'Popular': 'लोकप्रिय',
  'Trending': 'ट्रेंडिंग',
  'Featured': 'फीचर्ड',
  'Recommended': 'सुझाव',
  'Favorite': 'पसंदीदा',
  'Favourites': 'पसंदीदा',
  'Liked': 'पसंद किया',
  'Disliked': 'नापसंद किया',
  'Subscribe': 'सब्सक्राइब',
  'Unsubscribe': 'अनसब्सक्राइब',
  'Follow': 'फॉलो',
  'Unfollow': 'अनफॉलो',
  'Like': 'पसंद',
  'Unlike': 'नापसंद',
  'Comment': 'टिप्पणी',
  'Comments': 'टिप्पणियां',
  'Reply': 'जवाब',
  'Report': 'रिपोर्ट',
  'Block': 'ब्लॉक',
  'Unblock': 'अनब्लॉक',
  'Send': 'भेजें',
  'Receive': 'प्राप्त करें',
  'Message': 'संदेश',
  'Messages': 'संदेश',
  'Notification': 'सूचना',
  'Notifications': 'सूचनाएं',
  'Alert': 'अलर्ट',
  'Alerts': 'अलर्ट',
  'Update': 'अपडेट',
  'Updates': 'अपडेट',
  'Upgrade': 'अपग्रेड',
  'Downgrade': 'डाउनग्रेड',
  'Install': 'इंस्टॉल',
  'Uninstall': 'अनइंस्टॉल',
  'Sync': 'सिंक',
  'Backup': 'बैकअप',
  'Restore': 'रिस्टोर',
  'Import': 'इंपोर्ट',
  'Export': 'एक्सपोर्ट',
  'Copy': 'कॉपी',
  'Paste': 'पेस्ट',
  'Cut': 'कट',
  'Undo': 'अनडू',
  'Redo': 'रीडू',
  'Select': 'चुनें',
  'Select All': 'सभी चुनें',
  'Deselect': 'अचयन',
  'Deselect All': 'सभी अचयन',
  'Filter': 'फिल्टर',
  'Sort': 'क्रमबद्ध',
  'Group': 'ग्रुप',
  'Ungroup': 'अनग्रुप',
  'Zoom In': 'ज़ूम इन',
  'Zoom Out': 'ज़ूम आउट',
  'Fit to Screen': 'स्क्रीन में फिट',
  'Actual Size': 'वास्तविक आकार',
  'Preview': 'पूर्वावलोकन',
  'Print': 'प्रिंट',
  'Properties': 'गुण',
  'Details': 'विवरण',
  'Information': 'जानकारी',
  'Help': 'सहायता',
  'Support': 'समर्थन',
  'Documentation': 'दस्तावेज़',
  'Tutorial': 'ट्यूटोरियल',
  'Guide': 'गाइड',
  'FAQ': 'अक्सर पूछे जाने वाले प्रश्न',
  'Terms': 'शर्तें',
  'Privacy': 'गोपनीयता',
  'Policy': 'नीति',
  'License': 'लाइसेंस',
  'Copyright': 'कॉपीराइट',
  'All rights reserved': 'सभी अधिकार सुरक्षित',
  
  // Additional About Us translations
  'Geeta Bal Sanskar': 'गीता बाल संस्कार',
  'Spiritual Wisdom & Guidance': 'आध्यात्मिक ज्ञान और मार्गदर्शन',
  
  // Login/Logout translations
  'Are you sure you want to logout?': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
  'Login': 'लॉगिन',
  
  // Audio Categories
  'Bhajans': 'भजन',
  'Nitya Stuti': 'नित्य स्तुति',
  'Satsang': 'सत्संग',
  'Sandhya': 'संध्या',
  
  // Empty States
  'No data available': 'कोई डेटा उपलब्ध नहीं',
  'No content found': 'कोई सामग्री नहीं मिली',
  'Coming soon': 'जल्द आ रहा है',
  
  // Screen Content
  'Divine': 'दिव्य',
  'Sacred': 'पवित्र',
  'Daily': 'दैनिक',
  'Devotional songs': 'भक्ति गीत',
  'Spiritual practices': 'आध्यात्मिक अभ्यास',
  
  // Account Section
  'About': 'हमारे बारे में',
  'About Us': 'हमारे बारे में',
  'PDF Viewer': 'पीडीएफ व्यूअर',
  'Audio Player': 'ऑडियो प्लेयर',
  'Video Player': 'वीडियो प्लेयर',
  'Rate App': 'ऐप को रेट करें',
  'Share App': 'ऐप साझा करें',
  
  // About Screen Content
  'About the App': 'ऐप के बारे में',
  'Developer Information': 'डेवलपर जानकारी',
  'Contact': 'संपर्क',
  'Multiple language support': 'बहुभाषा समर्थन',
  'Dark and light theme options': 'डार्क और लाइट थीम विकल्प',
  'Offline content access': 'ऑफलाइन सामग्री पहुंच',
  
  // Report Issue Screen
  'Report Issue': 'समस्या रिपोर्ट करें',
  'Help us improve the app by reporting any issues you encounter.': 'आपको आने वाली किसी भी समस्या की रिपोर्ट करके ऐप को बेहतर बनाने में हमारी मदद करें।',
  'Issue Title': 'समस्या का शीर्षक',
  'Brief description of the issue': 'समस्या का संक्षिप्त विवरण',
  'Category': 'श्रेणी',
  'Description': 'विवरण',
  'Please describe the issue in detail...': 'कृपया समस्या का विस्तृत विवरण दें...',
  'Submit Report': 'रिपोर्ट जमा करें',
  'Please fill in all required fields': 'कृपया सभी आवश्यक फील्ड भरें',
  'Your issue has been reported successfully. We will get back to you soon.': 'आपकी समस्या सफलतापूर्वक रिपोर्ट कर दी गई है। हम जल्द ही आपसे संपर्क करेंगे।',
  'Failed to submit your report. Please try again.': 'आपकी रिपोर्ट जमा करने में विफल। कृपया पुनः प्रयास करें।',
  
  // Issue Categories
  'Bug Report': 'बग रिपोर्ट',
  'App Crash': 'ऐप क्रैश',
  'Audio Issue': 'ऑडियो समस्या',
  'Video Issue': 'वीडियो समस्या',
  'PDF Issue': 'पीडीएफ समस्या',
  'Login Problem': 'लॉगिन समस्या',
  'Other': 'अन्य',
  
  // Feature Request Screen
  'Feature Request': 'विशेषता अनुरोध',
  'Have an idea for a new feature? We\'d love to hear your suggestions!': 'क्या आपके पास कोई नई विशेषता का विचार है? हम आपके सुझाव सुनना पसंद करेंगे!',
  'Feature Title': 'विशेषता का शीर्षक',
  'Brief title for your feature idea': 'आपके विशेषता विचार का संक्षिप्त शीर्षक',
  'Priority': 'प्राथमिकता',
  'Feature Description': 'विशेषता विवरण',
  'Please describe your feature idea in detail. How would it work? What problem would it solve?': 'कृपया अपने विशेषता विचार का विस्तृत विवरण दें। यह कैसे काम करेगा? यह कौन सी समस्या हल करेगा?',
  'Submit Request': 'अनुरोध जमा करें',
  'Your feature request has been submitted successfully. Thank you for your suggestion!': 'आपका विशेषता अनुरोध सफलतापूर्वक जमा कर दिया गया है। आपके सुझाव के लिए धन्यवाद!',
  'Failed to submit your request. Please try again.': 'आपका अनुरोध जमा करने में विफल। कृपया पुनः प्रयास करें।',
  
  // Priority Levels
  'Low': 'कम',
  'Medium': 'मध्यम',
  'High': 'उच्च',
};

// Sanskrit translations
const sanskritTranslations: Record<string, string> = {
  'Geeta Bal Sanskar': 'गीता बाल संस्कारः',
  'Spiritual Wisdom & Guidance': 'आध्यात्मिक ज्ञानं मार्गदर्शनं च',
  'About': 'अस्माकं विषये',
  'About Us': 'अस्माकं विषये',
  'Settings': 'व्यवस्थाः',
  'Language': 'भाषा',
  'Appearance': 'रूपम्',
  'Help & Support': 'सहायता समर्थनं च',
  'Contact Us': 'अस्मान् सम्पर्कयतु',
  'Features': 'विशेषताः',
  'Mission': 'लक्ष्यम्',
  'Version': 'संस्करणम्',
  'Loading': 'लोडयति',
  'Light': 'प्रकाशः',
  'Dark': 'अन्धकारः',
  'System': 'प्रणाली',
  'Login': 'प्रवेशः',
  'Register': 'पञ्जीकरणम्',
  'Email': 'विद्युत्पत्रम्',
  'Cancel': 'निरस्तम्',
  'Share': 'साझाकरणम्',
  'Skip': 'त्यजतु',
  'Bhajans': 'भजनानि',
  'Mantras': 'मन्त्राः',
  'Prayers': 'प्रार्थनाः',
  'Meditation': 'ध्यानम्',
  'Yoga': 'योगः',
  'Wisdom': 'ज्ञानम्',
  'Peace': 'शान्तिः',
  'Love': 'प्रेम',
  'Truth': 'सत्यम्',
  'Dharma': 'धर्मः',
  'Karma': 'कर्म',
  'Divine': 'दिव्यम्',
  'Sacred': 'पवित्रम्',
  'Holy': 'पुण्यम्',
  'Ancient': 'प्राचीनम्',
  'Traditional': 'पारम्परिकम्',
  'Eternal': 'शाश्वतम्',
  'Universal': 'सार्वभौमिकम्',
  'Home': 'गृहम्',
  'Categories': 'वर्गाः',
  'Bookmarks': 'चिह्नानि',
  'Downloads': 'अवरोहणानि',
  'Search': 'अन्वेषणम्',
  'Profile': 'प्रोफाइलम्',
  'Account': 'खाता',
  'Logout': 'निर्गमनम्',
  'Back': 'पश्चात्',
  'Next': 'अग्रिमम्',
  'Previous': 'पूर्वम्',
  'Continue': 'चलतु',
  'Save': 'रक्षतु',
  'Delete': 'नाशयतु',
  'Edit': 'संपादयतु',
  'Add': 'योजयतु',
  'Remove': 'अपनयतु',
  'Close': 'बन्धयतु',
  'Open': 'उद्घाटयतु',
  'Play': 'वादयतु',
  'Pause': 'विरामयतु',
  'Stop': 'निवारयतु',
  'Replay': 'पुनर्वादयतु',
  'Download': 'अवरोहयतु',
  'Upload': 'उत्तोलयतु',
  'Refresh': 'नवीकरोति',
  'Retry': 'पुनर्यत्नयतु',
  'Error': 'दोषः',
  'Success': 'सिद्धिः',
  'Warning': 'चेतना',
  'Info': 'सूचना',
  'Yes': 'आम्',
  'No': 'न',
  'OK': 'अस्तु',
  'Done': 'समाप्तम्',
  'Finish': 'समाप्तिः',
  'Start': 'आरम्भः',
  'Begin': 'प्रारम्भः',
  'End': 'अन्तः',
  'Complete': 'पूर्णम्',
  'Incomplete': 'अपूर्णम्',
  'Available': 'उपलब्धम्',
  'Unavailable': 'अनुपलब्धम्',
  'Online': 'ऑनलाइन्',
  'Offline': 'ऑफलाइन्',
  'Connected': 'संयुक्तम्',
  'Disconnected': 'वियुक्तम्',
  'Welcome': 'स्वागतम्',
  'Hello': 'नमस्कारः',
  'Goodbye': 'पुनर्मिलामः',
  'Thank you': 'धन्यवादः',
  'Please': 'कृपया',
  'Sorry': 'क्षमा',
  'Excuse me': 'क्षमा करोतु',
  
  // Media types in Sanskrit
  'Audio': 'श्रव्यम्',
  'Video': 'दृश्यम्',
  'Image': 'चित्रम्',
  'Book': 'पुस्तकम्',
  'PDF': 'पीडीएफ्',
  'Music': 'संगीतम्',
  'Song': 'गीतम्',
  'Album': 'संग्रहः',
  'Artist': 'कलाकारः',
  'Author': 'लेखकः',
  'Title': 'शीर्षकम्',
  'Description': 'विवरणम्',
  'Duration': 'कालावधिः',
  'Size': 'मापम्',
  'Date': 'दिनाङ्कः',
  'Time': 'कालः',
  'Today': 'अद्य',
  'Yesterday': 'ह्यः',
  'Tomorrow': 'श्वः',
  'Week': 'सप्ताहः',
  'Month': 'मासः',
  'Year': 'वर्षम्',
  'Recently Played': 'साम्प्रति वादितम्',
  'Now Playing': 'साम्प्रति वाद्यमानम्',
  'Up Next': 'अग्रिमम्',
  'Playlist': 'वाद्यसूची',
  'Queue': 'पंक्तिः',
  'Shuffle': 'मिश्रणम्',
  'Repeat': 'पुनरावृत्तिः',
  'Volume': 'शब्दमात्रा',
  'Mute': 'मौनम्',
  'Unmute': 'अमौनम्',
  'Full Screen': 'पूर्ण पटलम्',
  'Exit Full Screen': 'पूर्ण पटलाद् बहिर्गमनम्',
  'Preferences': 'प्राथमिकताः',
  'Options': 'विकल्पाः',
  'Menu': 'सूची',
  'More': 'अधिकम्',
  'Less': 'न्यूनम्',
  'Show More': 'अधिकं दर्शयतु',
  'Show Less': 'न्यूनं दर्शयतु',
  'See All': 'सर्वं पश्यतु',
  'View All': 'सर्वं दृश्यताम्',
  'Hide': 'गुप्तम्',
  'Show': 'दर्शयतु',
  'Enable': 'सक्षमयतु',
  'Disable': 'असक्षमयतु',
  'On': 'चालितम्',
  'Off': 'बन्धम्',
  'Auto': 'स्वयंचालितम्',
  'Manual': 'हस्तचालितम्',
  'Default': 'मूलभूतम्',
  'Custom': 'अनुकूलितम्',
  'Reset': 'पुनर्निर्देशः',
  'Clear': 'निर्मलयतु',
  'Empty': 'शून्यम्',
  'Full': 'पूर्णम्',
  'New': 'नवीनम्',
  'Old': 'पुरातनम्',
  'Recent': 'साम्प्रतिकम्',
  'Popular': 'लोकप्रियम्',
  'Trending': 'प्रचलितम्',
  'Featured': 'विशिष्टम्',
  'Recommended': 'सिफारिशम्',
  'Favorite': 'प्रियम्',
  'Favourites': 'प्रियाणि',
  'Liked': 'प्रियं कृतम्',
  'Disliked': 'अप्रियं कृतम्',
  'Subscribe': 'अभिदानम्',
  'Unsubscribe': 'अभिदान निवृत्तिः',
  'Follow': 'अनुसरणम्',
  'Unfollow': 'अननुसरणम्',
  'Like': 'प्रियम्',
  'Unlike': 'अप्रियम्',
  'Comment': 'टिप्पणी',
  'Comments': 'टिप्पणियाः',
  'Reply': 'प्रतिउत्तरम्',
  'Report': 'विवरणम्',
  'Block': 'अवरोधः',
  'Unblock': 'अवरोध निवारणम्',
  'Send': 'प्रेषयतु',
  'Receive': 'गृह्णातु',
  'Message': 'संदेशः',
  
  // Audio Categories in Sanskrit
  'Bhajans': 'भजनानि',
  'Nitya Stuti': 'नित्य स्तुतिः',
  'Satsang': 'सत्सङ्गः',
  'Sandhya': 'सन्ध्या',
  
  // Empty States in Sanskrit
  'No data available': 'दत्तांशः न उपलब्धः',
  'No content found': 'विषयः न प्राप्तः',
  'Coming soon': 'शीघ्रमेव आगच्छति',
  
  // Screen Content in Sanskrit
  'Divine': 'दिव्यम्',
  'Sacred': 'पवित्रम्',
  'Daily': 'दैनिकम्',
  'Devotional songs': 'भक्ति गीतानि',
  'Spiritual practices': 'आध्यात्मिक अभ्यासाः',
  
  // Account Section in Sanskrit
  'PDF Viewer': 'पीडीएफ् दर्शकः',
  'Audio Player': 'श्रव्य वादकः',
  'Video Player': 'दृश्य वादकः',
  'Rate App': 'ऐप् मूल्याङ्कनम्',
  'Share App': 'ऐप् साझाकरणम्',
  
  // About Screen Content in Sanskrit
  'About the App': 'ऐप् विषये',
  'Developer Information': 'विकासक सूचना',
  'Contact': 'सम्पर्कः',
  'Multiple language support': 'बहुभाषा समर्थनम्',
  'Dark and light theme options': 'अन्धकार प्रकाश विकल्पाः',
  'Offline content access': 'ऑफलाइन् विषय प्रवेशः',
  
  // Long content translations
  'Geeta Bal Sanskar is a comprehensive spiritual learning platform that brings the timeless wisdom of the Bhagavad Gita to modern learners. Our app provides access to audio lectures, video content, and digital books to help you on your spiritual journey.': 'गीता बाल संस्कारः एकः सम्पूर्णः आध्यात्मिक शिक्षा मंचः अस्ति यः भगवद्गीतायाः शाश्वत ज्ञानं आधुनिक शिक्षार्थिभ्यः प्रदाति। अस्माकं ऐप् आध्यात्मिक यात्रायां सहायतार्थं श्रव्य भाषणानि, दृश्य विषयाणि, दिजिटल पुस्तकानि च प्रदाति।',
  'Our mission is to make spiritual knowledge accessible to everyone, everywhere. We believe that the teachings of the Bhagavad Gita can transform lives and bring peace, wisdom, and happiness to all who seek it.': 'अस्माकं लक्ष्यं आध्यात्मिक ज्ञानं सर्वेभ्यः सर्वत्र उपलब्धं कर्तुम् अस्ति। वयं मन्यामहे यत् भगवद्गीतायाः उपदेशाः जीवनानि परिवर्तयितुं शक्नुवन्ति तथा च सर्वेभ्यः अन्वेषिभ्यः शान्तिं, ज्ञानं, आनन्दं च आनेतुं शक्नुवन्ति।',
  
  // Feature list items
  '• Audio lectures and spiritual discourses': '• श्रव्य भाषणानि आध्यात्मिक प्रवचनानि च',
  '• Video content and teachings': '• दृश्य विषयाणि उपदेशाश्च',
  '• Digital books and PDFs': '• दिजिटल पुस्तकानि पीडीएफ् च',
  '• Multiple language support': '• बहुभाषा समर्थनम्',
  '• Dark and light theme options': '• अन्धकार प्रकाश विकल्पाः',
  '• Offline content access': '• ऑफलाइन् विषय प्रवेशः',
  
  // Help & Support Screen
  'Email Support': 'विद्युत्पत्र सहायता',
  'Website': 'वेबसाइट्',
  'Phone Support': 'दूरभाष सहायता',
  'Visit our official website': 'अस्माकं आधिकारिक वेबसाइट् दृश्यताम्',
  'Frequently Asked Questions': 'बहुधा पृष्टाः प्रश्नाः',
  'Quick Actions': 'त्वरित कर्माणि',
  'Report an Issue': 'समस्या निवेदनम्',
  'Request Feature': 'विशेषता अनुरोधः',
  
  // FAQ Questions and Answers
  'How do I download content for offline viewing?': 'ऑफलाइन् दर्शनार्थं विषयं कथम् अवरोहयामि?',
  'Tap the download icon next to any audio, video, or PDF content. Downloaded content will be available in the Downloads section.': 'कस्यापि श्रव्य, दृश्य, वा पीडीएफ् विषयस्य पार्श्वे अवरोहण चिह्नं स्पृशतु। अवरोहित विषयः अवरोहण विभागे उपलब्धः भविष्यति।',
  'Can I change the app language?': 'किमहं ऐप् भाषां परिवर्तयितुं शक्नोमि?',
  'Yes! Go to Settings > Language to select from available languages including Hindi, English, and Sanskrit.': 'आम्! हिन्दी, आंग्ल, संस्कृत आदि उपलब्ध भाषाभ्यः चयनार्थं व्यवस्था > भाषा गच्छतु।',
  'How do I switch between light and dark themes?': 'प्रकाश अन्धकार विषययोः मध्ये कथम् परिवर्तनं करोमि?',
  'Navigate to Settings > Appearance and choose between Light, Dark, or System theme options.': 'व्यवस्था > रूपम् गत्वा प्रकाश, अन्धकार, वा प्रणाली विषय विकल्पेभ्यः चिनुत।',
  'Is the content free to access?': 'किं विषयः निःशुल्कं प्राप्तुं शक्यते?',
  'Yes, all spiritual content including audio lectures, videos, and books are completely free to access.': 'आम्, श्रव्य भाषणानि, दृश्यानि, पुस्तकानि च सहितं सर्वं आध्यात्मिक विषयं पूर्णतया निःशुल्कं प्राप्तुं शक्यते।',
  'How do I report a technical issue?': 'तान्त्रिक समस्यां कथम् निवेदयामि?',
  'You can contact our support team using the contact options below or send us an email with details about the issue.': 'अधोलिखित सम्पर्क विकल्पान् उपयोगेन अस्माकं सहायता दलं सम्पर्कयितुं वा समस्यायाः विवरणैः सह अस्मान् विद्युत्पत्रं प्रेषयितुं शक्नुवन्ति।',
  
  // Report Issue Screen in Sanskrit
  'Report Issue': 'समस्या निवेदनम्',
  'Help us improve the app by reporting any issues you encounter.': 'भवद्भिः आगतान् समस्यान् निवेदयित्वा ऐप् उन्नतिं कर्तुं अस्मान् सहायताम्।',
  'Issue Title': 'समस्या शीर्षकम्',
  'Brief description of the issue': 'समस्यायाः संक्षिप्त विवरणम्',
  'Category': 'वर्गः',
  'Description': 'विवरणम्',
  'Please describe the issue in detail...': 'कृपया समस्यायाः विस्तृत विवरणं ददातु...',
  'Submit Report': 'निवेदनं प्रेषयतु',
  'Please fill in all required fields': 'कृपया सर्वानि आवश्यक क्षेत्राणि पूरयतु',
  'Your issue has been reported successfully. We will get back to you soon.': 'भवतः समस्या सफलतया निवेदिता। वयं शीघ्रमेव भवद्भिः सह सम्पर्कं करिष्यामः।',
  'Failed to submit your report. Please try again.': 'भवतः निवेदनं प्रेषयितुं असमर्थाः। कृपया पुनः प्रयत्नं करोतु।',
  
  // Issue Categories in Sanskrit
  'Bug Report': 'दोष निवेदनम्',
  'App Crash': 'ऐप् भङ्गः',
  'Audio Issue': 'श्रव्य समस्या',
  'Video Issue': 'दृश्य समस्या',
  'PDF Issue': 'पीडीएफ् समस्या',
  'Login Problem': 'प्रवेश समस्या',
  'Other': 'अन्यत्',
  
  // Feature Request Screen in Sanskrit
  'Feature Request': 'विशेषता अनुरोधः',
  'Have an idea for a new feature? We\'d love to hear your suggestions!': 'किम् भवतः नूतन विशेषतायाः विचारः अस्ति? वयं भवद्भिः सुझावान् श्रोतुं इच्छामः!',
  'Feature Title': 'विशेषता शीर्षकम्',
  'Brief title for your feature idea': 'भवद्भिः विशेषता विचारस्य संक्षिप्त शीर्षकम्',
  'Priority': 'प्राथमिकता',
  'Feature Description': 'विशेषता विवरणम्',
  'Please describe your feature idea in detail. How would it work? What problem would it solve?': 'कृपया भवद्भिः विशेषता विचारस्य विस्तृत विवरणं ददातु। किम् एतत् कथं कार्यं करिष्यति? किम् समस्यां समाधास्यति?',
  'Submit Request': 'अनुरोधं प्रेषयतु',
  'Your feature request has been submitted successfully. Thank you for your suggestion!': 'भवतः विशेषता अनुरोधः सफलतया प्रेषितः। भवद्भिः सुझावाय धन्यवादाः!',
  'Failed to submit your request. Please try again.': 'भवद्भिः अनुरोधं प्रेषयितुं असमर्थाः। कृपया पुनः प्रयत्नं करोतु।',
  
  // Priority Levels in Sanskrit
  'Low': 'न्यूनम्',
  'Medium': 'मध्यमम्',
  'High': 'उच्चम्',
  
  // Audio Categories in Sanskrit
  'Nitya Stuti': 'नित्य स्तुतिः',
  'Satsang': 'सत्सङ्गः',
  'Sandhya': 'सन्ध्या',
  
  // Empty States in Sanskrit
  'No data available': 'दत्तांशः न उपलब्धः',
  'No content found': 'विषयः न प्राप्तः',
  'Coming soon': 'शीघ्रमेव आगच्छति',
  
  // Screen Content in Sanskrit
  'Divine': 'दिव्यम्',
  'Sacred': 'पवित्रम्',
  'Daily': 'दैनिकम्',
  'Devotional songs': 'भक्ति गीतानि',
  'Spiritual practices': 'आध्यात्मिक अभ्यासाः',
  'Messages': 'संदेशाः',
  'Notification': 'सूचना',
  'Notifications': 'सूचनाः',
  'Alert': 'चेतना',
  'Alerts': 'चेतनाः',
  'Update': 'अद्यतनम्',
  'Updates': 'अद्यतनानि',
  'Upgrade': 'उन्नयनम्',
  'Downgrade': 'अवनयनम्',
  'Install': 'स्थापनम्',
  'Uninstall': 'अपसारणम्',
  'Sync': 'समकालीकरणम्',
  'Backup': 'संरक्षणम्',
  'Restore': 'पुनरुद्धारः',
  'Import': 'आयातम्',
  'Export': 'निर्यातम्',
  'Copy': 'प्रतिलिपिः',
  'Paste': 'संलग्नयतु',
  'Cut': 'छिद्यताम्',
  'Undo': 'पूर्ववत्',
  'Redo': 'पुनरावृत्तिः',
  'Select': 'चिनोतु',
  'Select All': 'सर्वं चिनोतु',
  'Deselect': 'अचयनम्',
  'Deselect All': 'सर्व अचयनम्',
  'Filter': 'परिशोधकम्',
  'Sort': 'क्रमबद्धता',
  'Group': 'समूहः',
  'Ungroup': 'विभाजनम्',
  'Zoom In': 'विस्तारणम्',
  'Zoom Out': 'संकोचनम्',
  'Fit to Screen': 'पटले योज्यम्',
  'Actual Size': 'वास्तविक मापम्',
  'Preview': 'पूर्वावलोकनम्',
  'Print': 'मुद्रणम्',
  'Properties': 'गुणाः',
  'Details': 'विस्ताराः',
  'Information': 'सूचना',
  'Help': 'सहायता',
  'Support': 'समर्थनम्',
  'Documentation': 'दस्तावेजीकरणम्',
  'Tutorial': 'शिक्षणम्',
  'Guide': 'मार्गदर्शिका',
  'FAQ': 'बहुधा पृष्टाः प्रश्नाः',
  'Terms': 'शर्ताः',
  'Privacy': 'गोपनीयता',
  'Policy': 'नीतिः',
  'License': 'अनुज्ञापत्रम्',
  'Copyright': 'कॉपीराइट्',
  'All rights reserved': 'सर्वाणि अधिकाराणि सुरक्षितानि',
};

/**
 * Translates content based on current language
 */
export const translateContent = (text: string): string => {
  if (!text || typeof text !== 'string') return text;
  
  const currentLanguage = i18n.language;
  
  // Sanskrit translations
  if (currentLanguage === 'sa') {
    if (sanskritTranslations[text]) {
      return sanskritTranslations[text];
    }
    
    const lowerText = text.toLowerCase();
    const matchingKey = Object.keys(sanskritTranslations).find(
      key => key.toLowerCase() === lowerText
    );
    if (matchingKey) {
      return sanskritTranslations[matchingKey];
    }
  }
  
  // Hindi translations
  if (currentLanguage === 'hi') {
    if (contentTranslations[text]) {
      return contentTranslations[text];
    }
    
    const lowerText = text.toLowerCase();
    const matchingKey = Object.keys(contentTranslations).find(
      key => key.toLowerCase() === lowerText
    );
    if (matchingKey) {
      return contentTranslations[matchingKey];
    }
    
    for (const [english, hindi] of Object.entries(contentTranslations)) {
      if (text.toLowerCase().includes(english.toLowerCase()) && english.length > 3) {
        return text.replace(new RegExp(english, 'gi'), hindi);
      }
    }
  }
  
  return text;
};

/**
 * Translates an object's specific fields
 */
export const translateObject = <T extends Record<string, any>>(
  obj: T,
  fieldsToTranslate: (keyof T)[] = ['title', 'description', 'name']
): T => {
  const translated = { ...obj };
  
  fieldsToTranslate.forEach(field => {
    if (translated[field] && typeof translated[field] === 'string') {
      (translated as any)[field] = translateContent(translated[field] as string);
    }
  });
  
  return translated;
};

/**
 * Translates an array of objects
 */
export const translateArray = <T extends Record<string, any>>(
  array: T[],
  fieldsToTranslate?: (keyof T)[]
): T[] => {
  return array.map(item => translateObject(item, fieldsToTranslate));
};

/**
 * Adds more translations dynamically
 */
export const addTranslations = (translations: Record<string, string>) => {
  Object.assign(contentTranslations, translations);
};

/**
 * Gets all available translations
 */
export const getTranslations = () => contentTranslations;

/**
 * Checks if a translation exists for given text
 */
export const hasTranslation = (text: string): boolean => {
  if (!text || typeof text !== 'string') return false;
  return contentTranslations.hasOwnProperty(text) || 
         Object.keys(contentTranslations).some(key => key.toLowerCase() === text.toLowerCase());
};